### ISSUE TITLE
Invalid `immutable_date(time)` cast parsing

### ISSUE THREAD

**Issue by edwinvdpol** [Soyhuce/next-ide-helper#102]
Hi there,

When I define a mutator like `immutable_date` is it not parsed as `Carbon\CarbonImmutable`, but as `mixed`.
When I define a mutator like `immutable_date:Y-m-d` is it not parsed as `Carbon\CarbonImmutable`, but as `mixed`.
When I define a mutator like `immutable_datetime` is it not parsed as `Carbon\CarbonImmutable`, but as `mixed`.
When I define a mutator like `immutable_datetime:Y-m-d H:i:s` is it not parsed as `Carbon\CarbonImmutable`, but as `mixed`.

_Without_ the `immutable_` prefix, it works correctly.

When I tinker the following, it gives the correct result: `Carbon\CarbonImmutable`
```php
Date::now()->toImmutable();
```

Any ideas? Not sure why this happens (again).

**Comment by bastien-phi** [comment]
Which version are you using ?

**Comment by edwinvdpol** [comment]
Ah, never mind! You are right, I was still on `0.14.0`.

When you install this package, it automatically uses the `"^0.15.4` notation. Maybe change this to `^0.15` if possible?
Right now, it does not update the minor versions, which should be backwards compatible?

Just my 2 cents, and thanks again.
