### ISSUE TITLE
Model factory not correct

### ISSUE THREAD

**Issue by edwinvdpol** [Soyhuce/next-ide-helper#45]
Hi there,

I just installed this package, which I am testing instead of the original IDE helper.
I noticed that the factory classes is not correct:

`* @method static \Database\Factories\Models\UserFactory factory($count = 1, $state = [])`

This should be

`* @method static \Database\Factories\UserFactory factory($count = 1, $state = [])`

I am using Laravel 8.
In my config, I have entered the `app/Models` as my models directory.

Keep up the good work! :-D

**Comment by bastien-phi** [comment]
Indeed, there is an issue with that. I will fix it.

**Comment by bastien-phi** [comment]
The fix was released in 0.7.1
