### ISSUE TITLE
Attribute method visibility problem

### ISSUE THREAD

**Issue by edwinvdpol** [Soyhuce/next-ide-helper#67]
Hi 👋 

I noticed my `property-reads` were removed when I generate the docblocks for my models when I use the `Attribute` return type (#43).

This problem is caused by the visibility of the "Attribute method".

On the Laravel documentation website, it [states](https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor) that the property must be defined as `protected`, not `public`.

Is there any way to fix this problem? ;-)

I created an PR where the test _should_ pass.

Thanks!

**Comment by bastien-phi** [comment]
Thanks for the report, I will check that.

**Comment by bastien-phi** [comment]
Fixed in #68 and release in version 0.11.1

**Comment by edwinvdpol** [comment]
That was quick, thank you!
