### ISSUE TITLE
Tinyint does not automatically mean it's a boolean

### ISSUE THREAD

**Issue by JapSeyz** [Soyhuce/next-ide-helper#86]
Hi,

When generating model attributes, it seems to always expect a tinyInt column in the DB to represent a boolean. However it can also be used to represent small numbers. like week numbers and months.

When it's assumed to always be a boolean, you get issues like the follwing, when using it as months:
<img width="683" alt="image" src="https://github.com/Soyhuce/next-ide-helper/assets/2234034/0ebb4d9a-2f1b-4bc5-a724-db8bcf82b451">

**Comment by bastien-phi** [comment]
Hi there !

I tried to reproduce your error. Unfortunately, the package does resolve tinyInt column as a php integer : https://github.com/Soyhuce/next-ide-helper/pull/87

Which database are you using ? Which version of this package are you using ?

**Comment by bastien-phi** [comment]
closed by inactivity
