### ISSUE TITLE
ReflectionException while running the models command

### ISSUE THREAD

**Issue by vivere-dally** [Soyhuce/next-ide-helper#97]
`php artisan next-ide-helper:models`
 
> ReflectionException
Class "CreateWalleeTransactionsTable" does not exist
at vendor/soyhuce/next-ide-helper/src/Domain/Models/Actions/FindModels.php:38
     34▕      * @param class-string $class
     35▕      */
     36▕     private function isEloquentModel(string $class): bool
     37▕     {
➜ 38▕         $reflexion = new ReflectionClass($class);
     39▕
     40▕         if (!$reflexion->isSubclassOf(EloquentModel::class)) {
     41▕             return false;
     42▕         }
+15 vendor frames
   16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by bastien-phi** [comment]
Released in 0.15.2
